name:  'recipe-app'
services:
  frontend:
    build: ./frontend
    container_name: recipe-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    container_name: recipe-backend
    ports:
      - "5000:5000"
    env_file: 
      - ./env/backend.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  mysql:
    image: mysql:latest
    container_name: mysql-server
    env_file:
      -  ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "student", "--password=student"]
      interval: 10s
      timeout: 10s
      retries: 6

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
